name: Mirror to Gitee Repo

on:
  push:
    branches: [main, master]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:chengzao/imgbed.git
          destination-repo: git@gitee.com:cxyz/imgbed.git